### PR TITLE
8276141: XPathFactory set/getProperty method

### PR DESCRIPTION
**Pull request by yan-too**
Difference against the original: no LastModified in XPathFactoryImpl.java in 13/15; the test patch manually applied.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8276141](https://bugs.openjdk.java.net/browse/JDK-8276141): XPathFactory set/getProperty method
 * [JDK-8276143](https://bugs.openjdk.java.net/browse/JDK-8276143): Add XPathFactory setProperty and getProperty methods (**CSR**)

### Reviewers
 * [Andrew Brygin](https://openjdk.java.net/census#bae) (@bae - **Reviewer**)
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk13u-dev pull/329/head:pull/329` \
`$ git checkout pull/329`

Update a local copy of the PR: \
`$ git checkout pull/329` \
`$ git pull https://git.openjdk.java.net/jdk13u-dev pull/329/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 329`

View PR using the GUI difftool: \
`$ git pr show -t 329`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk13u-dev/pull/329.diff">https://git.openjdk.java.net/jdk13u-dev/pull/329.diff</a>

</details>

### CODE REVIEW

**Review by bae — APPROVED** [review]
The proposed change looks fine.

Thanks,
Andrew

**Review by GoeLin — APPROVED** [review]
LGTM

**Review by bae — APPROVED** [review]
Looks fine.

**Pull request closed without merging**
