### PR TITLE
8236859: WebSocket over authenticating proxy fails with NPE

### PR DESCRIPTION
**Pull request by Larry-N**
Backport fix for bug 8236859
+ small correction  cache.store() calling because of method signature difference from 16 to 13 jdk. 
File: AuthenticationFilter.java

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8236859](https://bugs.openjdk.java.net/browse/JDK-8236859): WebSocket over authenticating proxy fails with NPE

### Reviewers
 * [Yuri Nesterenko](https://openjdk.java.net/census#yan) (@yan-too - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk13u-dev pull/53/head:pull/53`
`$ git checkout pull/53`

### CODE REVIEW

**Comment by robilad** [comment]
Hi,

Please send me an email to dalibor.topic@oracle.com so that I can verify your account.

**Review by yan-too — APPROVED** [review]

**Pull request closed without merging**
