### PR TITLE
8202343: Disable TLS 1.0 and 1.1

### PR DESCRIPTION
**Pull request by alvdavi**
I'd like to backport 8202343 to jdk13u. All other jdk versions are disabling TLS 1.0 and TLS 1.1 in 2021 April CPU.

The patch did not apply cleanly. I had to account for JDK-8235710 missing in 13u, affecting the java.security file. Additionally, JDK-8243029 is also missing, so some of the tests modified do not exist in 13u.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8202343](https://bugs.openjdk.java.net/browse/JDK-8202343): Disable TLS 1.0 and 1.1 ⚠️ Issue is not open.

### Reviewers
 * [Yuri Nesterenko](https://openjdk.java.net/census#yan) (@yan-too - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk13u-dev pull/143/head:pull/143` \
`$ git checkout pull/143`

Update a local copy of the PR: \
`$ git checkout pull/143` \
`$ git pull https://git.openjdk.java.net/jdk13u-dev pull/143/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 143`

View PR using the GUI difftool: \
`$ git pr show -t 143`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk13u-dev/pull/143.diff">https://git.openjdk.java.net/jdk13u-dev/pull/143.diff</a>

</details>

### CODE REVIEW

**Comment by yan-too** [comment]
created https://bugs.openjdk.java.net/browse/SKARA-929

**Comment by alvdavi** [comment]
@yan-too, as the 13.0.7 is getting closer, feel free to close this pull request and manually grab JDK-8202343

**Comment by yan-too** [comment]
@alvdavi We have several days for critical, perhaps they will process the oca  request, after all. If not, thank you, I'll grab it at the last moment

**Comment by robilad** [comment]
Apologies for the delay.

I re-pinged Yishai to verify your account @aldavi.

**Review by yan-too — APPROVED** [review]
Fine as far as I see. 
Will go to 13.0.8, first buid

**Pull request closed without merging**
