### PR TITLE
8253528: Update .jcheck/conf for jdk13u-dev

### PR DESCRIPTION
**Pull request by rwestberg**
Hi all,

Please review this initial jcheck configuration for use with the Skara tooling.

Best regards,
Robin

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253528](https://bugs.openjdk.java.net/browse/JDK-8253528): Update .jcheck/conf for jdk13u-dev

### Reviewers
 * [Yuri Nesterenko](https://openjdk.java.net/census#yan) (@yan-too - **Reviewer**)
 * [Erik Helin](https://openjdk.java.net/census#ehelin) (@edvbld - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk13u-dev pull/1/head:pull/1`
`$ git checkout pull/1`

### CODE REVIEW

**Review by yan-too — APPROVED** [review]

**Comment by yan-too** [comment]
Note that the first line looks 
rwestberg wants to merge 1 commit into openjdk:master
while the link is, as expected, https://github.com/openjdk/jdk13u-dev
Not a big deal though, the name of repo is everywhere

**Review by edvbld — APPROVED** [review]
Looks good!

**Pull request closed without merging**
